/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.book.ui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import poly.book.component.ImageJPanel;
import poly.book.util.XAuth;
import poly.book.util.XIcon;

/**
 *
 * @author Dell
 */
public class PolyBookJFram1 extends javax.swing.JFrame implements PolyBookController{

    /**
     * Creates new form PolyBookJFram1
     */
    public PolyBookJFram1() {
       initComponents();
    init(); // GỌI INIT Ở ĐÂY ✅
    setTitle("Poly Book");
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCenter = new javax.swing.JPanel();
        pnlPhoto = new poly.book.component.ImageJPanel();
        lblFullname = new javax.swing.JLabel();
        btnBill = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pnlManager = new javax.swing.JPanel();
        btnCateroryManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnBookManager = new javax.swing.JButton();
        btnCustomerManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCenter.add(pnlPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 133));

        lblFullname.setText("Lê Ngọc Trân");
        pnlCenter.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnBill.setBackground(new java.awt.Color(153, 204, 255));
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Icojam-Blueberry-Basic-Shopping-cart.32.png"))); // NOI18N
        btnBill.setText("BÁN HÀNG");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        pnlCenter.add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 201, 200, -1));

        btnChangePassword.setBackground(new java.awt.Color(153, 204, 255));
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Fatcow-Farm-Fresh-Change-password.32.png"))); // NOI18N
        btnChangePassword.setText("ĐỔI MẬT KHẨU");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlCenter.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, -1));

        btnHistory.setBackground(new java.awt.Color(153, 204, 255));
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/URL-history-icon.png"))); // NOI18N
        btnHistory.setText("XEM LỊCH SỬ");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        pnlCenter.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, -1));

        btnExit.setBackground(new java.awt.Color(153, 204, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Icon Application/Icon Application/Exit.png"))); // NOI18N
        btnExit.setText("KẾT THÚC");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlCenter.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        pnlCenter.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 10));

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        pnlManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCateroryManager.setBackground(new java.awt.Color(153, 204, 255));
        btnCateroryManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Books-icon.png"))); // NOI18N
        btnCateroryManager.setText("LOẠI SÁCH");
        btnCateroryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateroryManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCateroryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

        btnUserManager.setBackground(new java.awt.Color(153, 204, 255));
        btnUserManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/add-user-icon.png"))); // NOI18N
        btnUserManager.setText("NGƯỜI DÙNG");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, -1));

        btnBillManager.setBackground(new java.awt.Color(153, 204, 255));
        btnBillManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Icojam-Blueberry-Basic-Shopping-cart.32.png"))); // NOI18N
        btnBillManager.setText("HÓA ĐƠN");
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnBillManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 150, -1));

        btnBookManager.setBackground(new java.awt.Color(153, 204, 255));
        btnBookManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Book-icon.png"))); // NOI18N
        btnBookManager.setText("TÊN SÁCH");
        btnBookManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnBookManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 150, -1));

        btnCustomerManager.setBackground(new java.awt.Color(153, 204, 255));
        btnCustomerManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Etherbrian-Toys-Lil-people.32.png"))); // NOI18N
        btnCustomerManager.setText("KHÁCH HÀNG");
        btnCustomerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCustomerManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 150, -1));

        btnRevenueManager.setBackground(new java.awt.Color(153, 204, 255));
        btnRevenueManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/Wefunction-Woofunction-Save-upload.32.png"))); // NOI18N
        btnRevenueManager.setText("DOANH THU");
        btnRevenueManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnRevenueManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons/paner.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        pnlManager.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2160, -1));

        getContentPane().add(pnlManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 640, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCateroryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateroryManagerActionPerformed
        // TODO add your handling code here:
        this.showCategoryManagerJDialog(this);
    }//GEN-LAST:event_btnCateroryManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnBookManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookManagerActionPerformed
        // TODO add your handling code here:
        this.showBookManagerJDialog(this);
    }//GEN-LAST:event_btnBookManagerActionPerformed

    private void btnCustomerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagerActionPerformed
        // TODO add your handling code here:
        this.showCustomerManagerJDialog(this);
    }//GEN-LAST:event_btnCustomerManagerActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        // TODO add your handling code here:
        this.showBillManagerJDialog(this);
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnRevenueManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueManagerActionPerformed
        // TODO add your handling code here:
        this.showRevenueManagerJDialog(this);
    }//GEN-LAST:event_btnRevenueManagerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        this.showBillJDialog(this);
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
      ChangePasswordJDialog dialog = new ChangePasswordJDialog(this, true);
    if (XAuth.user != null) {
        dialog.setUsername(XAuth.user.getUsername()); // ✅ truyền tên đăng nhập
    }
    dialog.setVisible(true); // hoặc dialog.open(); tùy bạn dùng cách nào
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        this.showHistoryJDialog(this);
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyBookJFram1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyBookJFram1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyBookJFram1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyBookJFram1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PolyBookJFram1().setVisible(true);
            }
        });
    }

@Override
public void init() {
    this.setIconImage(XIcon.getIcon("trump-small.png").getImage());
    this.setLocationRelativeTo(null);

    this.showWelcomeJDialog(this);
    this.showLoginJDialog(this);

    if (XAuth.user == null) {
        System.exit(0);
    }

    // Hiển thị ảnh người dùng
    String photoName = XAuth.user.getPhoto();
    URL imageUrl = getClass().getResource("/images/" + photoName);

    if (imageUrl != null) {
        ImageIcon icon = new ImageIcon(imageUrl);
        ((ImageJPanel) pnlPhoto).setImage(icon.getImage());
    } else {
        System.err.println("Không tìm thấy ảnh user: " + photoName + ", load ảnh mặc định.");
        URL defaultUrl = getClass().getResource("/images/default.png");
        if (defaultUrl != null) {
            ImageIcon defaultIcon = new ImageIcon(defaultUrl);
            ((ImageJPanel) pnlPhoto).setImage(defaultIcon.getImage());
        } else {
            ((ImageJPanel) pnlPhoto).setImage(null);
        }
    }

    // Hiển thị tên
    lblFullname.setText( XAuth.user.getFullName());

    // PHÂN QUYỀN: Ẩn panel quản lý nếu không phải Quản lý
    if (!XAuth.user.isManager()) {
    btnCateroryManager.setVisible(false);
    btnUserManager.setVisible(false);
    btnBillManager.setVisible(false);
    btnBookManager.setVisible(false);
    btnCustomerManager.setVisible(false);
    btnRevenueManager.setVisible(false);
 
}
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnBookManager;
    private javax.swing.JButton btnCateroryManager;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCustomerManager;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlManager;
    private poly.book.component.ImageJPanel pnlPhoto;
    // End of variables declaration//GEN-END:variables
}
